### Login request
POST http://{{API_URL}}/login
Content-Type: application/json

{
  "email": "pandeymp1996@gmail.com",
  "password": "admin"
}

### Register request
POST http://{{API_URL}}/register
Content-Type: application/json

{
  "name": "Mohit",
  "email": "mohitpmp3@gmail.com",
  "password": "123456789",
  "city": "Haldwani",
  "state": "Uttarakhand",
  "zip": "263139",
  "country": "India",
  "mobile": "7983848236",
  "address": "xyz"
}

### Get categories list request
GET http://{{API_URL}}/getCategories
Accept: application/json
Authorization: Bearer {{APP_TOKEN}}

### Get subcategories by category id request
GET http://{{API_URL}}/getSubCategoriesByID/61d1b3cccfa792063ca5d867
Accept: application/json
Authorization: Bearer {{APP_TOKEN}}

### Get products by subcategory id request
GET http://{{API_URL}}/getProductsBySubcategoryID/61f806aa3167801bf064f801
Accept: application/json
Authorization: Bearer {{APP_TOKEN}}

### Get product details by id request
GET http://{{API_URL}}/getProductDetails/61d1bb34cfa792063ca5d86d
Accept: application/json
Authorization: Bearer {{APP_TOKEN}}

###